type User @collection(name: "users") {
  name: String!
  username: String! @unique(index: "unique_username")
  email: String! @unique(index: "unique_email")
  password: String!
  photo_url: String
  tweets: [Tweet!] @relation(name: "user_tweets")
}

type Tweet @collection(name: "tweets") {
  author: User @relation(name: "user_tweets")
  content: String!
}

type Query {
  allTweets: [Tweet]
  allPersons: [User]
}
